region:
  longitude_start: 234
  longitude_end: 294
  latitude_start: 22.5
  latitude_end: 52.5
  input_resolution_degrees: 1.5
  output_resolution_degrees: 0.25

train_data:
  hourly_dataset_path: "/super_resolution/training/example_dataset/era5_hourly_normalized_residuals.zarr"
  hourly_variables:
    - # temperature
      - "2m_temperature"
      - null
      - "hourly_2mT"
    - # wind speed
      - "10m_magnitude_of_wind"
      - null
      - "hourly_10mW"
    - # specific humidity
      - "specific_humidity"
      - level:
        - 1000
      - "hourly_Q1000"
    - # sea level pressure
      - "mean_sea_level_pressure"
      - null
      - "hourly_MSL"
  hourly_downsample: 2
  hourly_data_std: 1.0
  daily_dataset_path: "/super_resolution/training/example_dataset/era5_daily.zarr"
  daily_variables:
    - # temperature
      - "2m_temperature"
      - null
      - "daily_2mT"
    - # wind speed
      - "10m_magnitude_of_wind"
      - null
      - "daily_10mW"
    - # specific humidity
      - "specific_humidity"
      - level:
        - 1000
      - "daily_Q1000"
    - # sea level pressure
      - "mean_sea_level_pressure"
      - null
      - "daily_MSL"
  daily_stats_path: "/super_resolution/training/example_dataset/era5_daily_stats.zarr"
  num_days_per_example: 7
  date_range:
    - "1961-01-01"
    - "1999-12-31"
  batch_size: 1
  shuffle: true
  worker_count: 0
  rng_seed: 12
  cond_maskout_prob: 0.1

eval_data:
  hourly_dataset_path: "/super_resolution/training/example_dataset/era5_hourly_normalized_residuals.zarr"
  hourly_variables:
    - # temperature
      - "2m_temperature"
      - null
      - "hourly_2mT"
    - # wind speed
      - "10m_magnitude_of_wind"
      - null
      - "hourly_10mW"
    - # specific humidity
      - "specific_humidity"
      - level:
        - 1000
      - "hourly_Q1000"
    - # sea level pressure
      - "mean_sea_level_pressure"
      - null
      - "hourly_MSL"
  hourly_downsample: 2
  hourly_data_std: 1.0
  daily_dataset_path: "/super_resolution/training/example_dataset/era5_daily.zarr"
  daily_variables:
    - # temperature
      - "2m_temperature"
      - null
      - "daily_2mT"
    - # wind speed
      - "10m_magnitude_of_wind"
      - null
      - "daily_10mW"
    - # specific humidity
      - "specific_humidity"
      - level:
        - 1000
      - "daily_Q1000"
    - # sea level pressure
      - "mean_sea_level_pressure"
      - null
      - "daily_MSL"
  daily_stats_path: "/super_resolution/training/example_dataset/era5_daily_stats.zarr"
  num_days_per_example: 7
  date_range:
    - "1961-01-01"
    - "1999-12-31"
  batch_size: 1
  shuffle: true
  worker_count: 0
  rng_seed: 34
  cond_maskout_prob: 0.1

model:
  num_days: 7
  hour_interval: 2
  skip_interp_method: "linear"
  num_output_channels: 4
  sample_resize: null
  num_latent_channels:
    - 128
    - 256
    - 384
    - 512
  downsample_ratio:
    - 3
    - 2
    - 2
    - 2
  num_blocks: 4
  noise_embedding_dim: 128
  num_input_projection_channels: 128
  num_output_projection_channels: 128
  padding: "SAME"
  use_spatial_attention:
    - false
    - false
    - true
    - true
  use_temporal_attention:
    - false
    - false
    - true
    - true
  use_positional_encoding: true
  num_attention_heads: 8
  normalize_qk: true
  cond_resize_method: "nearest"
  cond_embedding_dim: 128

training:
  work_dir: "/super_resolution/training/conus_7d_t2m_w10m_q1000_msl"
  total_train_steps: 100000
  checkpoint_every_n_steps: 500
  checkpoint_max_to_keep: 5
  trainer_rng_seed: 56
  lr_initial: 0.0
  lr_peak: 0.0001
  lr_end: 0.0000001
  lr_warmup_steps: 1000
  clip_grad_norm: 0.6
  train_max_noise_level: 80.0
  ema_decay: 0.9999
  eval_every_n_steps: 1000
  eval_num_batches_per_step: 1
  eval_num_sde_steps: 128
  eval_num_samples_per_condition: 1
  eval_num_ode_steps: 64
  eval_cfg_strength: 0.2
  eval_num_likelihood_probes: 1
