region:
  longitude_start: 260
  longitude_end: 350
  latitude_start: 5
  latitude_end: 50
  input_resolution_degrees: 1.5
  output_resolution_degrees: 0.25

# Hourly dataset: we assume that the dataset has been preprocessed offline:
# - Difference is taken between hourly and interpolated (linearly in space and replicated in time)
#   daily daily data.
# - The residuals are normalized with respect to its own climatology (specific to day of the year
#    and time of the day).
# The resulting hourly data should have approximately mean 0 and standard deviation 1.
train_data:
  hourly_dataset_path: "/super_resolution/training/example_dataset/era5_0p25deg_residual_1980-2009_nao_t2m_w10m_q1000_msl_z200_z500.zarr"
  hourly_variables:
    - # temperature
      - "2m_temperature"
      - null
      - "hourly_t2m"
    - # wind speed
      - "10m_magnitude_of_wind"
      - null
      - "hourly_w10m"
    - # specific humidity @ 1000hPa
      - "specific_humidity"
      - level:
        - 1000
      - "hourly_q1000"
    - # sea level pressure
      - "mean_sea_level_pressure"
      - null
      - "hourly_msl"
    - # geopotential @ 200hPa
      - "geopotential"
      - level:
        - 200
      - "hourly_z200"
    - # geopotential @ 500hPa
      - "geopotential"
      - level:
        - 500
      - "hourly_z500"
  hourly_downsample: 2
  hourly_data_std: 1.0
  daily_dataset_path: "/super_resolution/training/example_dataset/era5_1p5deg_1980-2009_global_t2m_w10m_q1000_msl_z200_z500.zarr"
  daily_variables:
    - # temperature
      - "2m_temperature"
      - null
      - "daily_t2m"
    - # wind speed
      - "10m_magnitude_of_wind"
      - null
      - "daily_w10m"
    - # specific humidity
      - "specific_humidity"
      - level:
        - 1000
      - "daily_q1000"
    - # sea level pressure
      - "mean_sea_level_pressure"
      - null
      - "daily_msl"
    - # geopotential @ 200hPa
      - "geopotential"
      - level:
        - 200
      - "daily_z200"
    - # geopotential @ 500hPa
      - "geopotential"
      - level:
        - 500
      - "daily_z500"
  daily_stats_path: "/super_resolution/training/example_dataset/era5_1p5deg_1980-2009_global_t2m_w10m_q1000_msl_z200_z500.zarr"
  num_days_per_example: 7
  date_range:
    - "1980-01-01"
    - "1999-12-31"
  batch_size: 1
  shuffle: true
  worker_count: 0
  rng_seed: 21
  cond_maskout_prob: 0.1

eval_data:
  hourly_dataset_path: "/super_resolution/training/example_dataset/era5_0p25deg_residual_1980-2009_nao_t2m_w10m_q1000_msl_z200_z500.zarr"
  hourly_variables:
    - # temperature
      - "2m_temperature"
      - null
      - "hourly_t2m"
    - # wind speed
      - "10m_magnitude_of_wind"
      - null
      - "hourly_w10m"
    - # specific humidity
      - "specific_humidity"
      - level:
        - 1000
      - "hourly_q1000"
    - # sea level pressure
      - "mean_sea_level_pressure"
      - null
      - "hourly_msl"
    - # geopotential @ 200hPa
      - "geopotential"
      - level:
        - 200
      - "hourly_z200"
    - # geopotential @ 500hPa
      - "geopotential"
      - level:
        - 500
      - "hourly_z500"
  hourly_downsample: 2
  hourly_data_std: 1.0
  daily_dataset_path: "/super_resolution/training/example_dataset/era5_1p5deg_1980-2009_global_t2m_w10m_q1000_msl_z200_z500.zarr"
  daily_variables:
    - # temperature
      - "2m_temperature"
      - null
      - "daily_t2m"
    - # wind speed
      - "10m_magnitude_of_wind"
      - null
      - "daily_w10m"
    - # specific humidity
      - "specific_humidity"
      - level:
        - 1000
      - "daily_q1000"
    - # sea level pressure
      - "mean_sea_level_pressure"
      - null
      - "daily_msl"
    - # geopotential @ 200hPa
      - "geopotential"
      - level:
        - 200
      - "daily_z200"
    - # geopotential @ 500hPa
      - "geopotential"
      - level:
        - 500
      - "daily_z500"
  daily_stats_path: "/super_resolution/training/example_dataset/era5_1p5deg_stats_global_t2m_w10m_q1000_msl_z200_z500.zarr"
  num_days_per_example: 7
  date_range:
    - "2000-01-01"
    - "2009-12-31"
  batch_size: 1
  shuffle: true
  worker_count: 0
  rng_seed: 34
  cond_maskout_prob: 0.1

model:
  num_days: 7
  hour_interval: 2
  skip_interp_method: "linear"
  num_output_channels: 6
  sample_resize: null
  num_latent_channels:
    - 128
    - 256
    - 384
    - 512
  downsample_ratio:
    - 3
    - 3
    - 2
    - 2
  num_blocks: 4
  noise_embedding_dim: 128
  num_input_projection_channels: 128
  num_output_projection_channels: 128
  padding: "SAME"
  use_spatial_attention:
    - false
    - false
    - true
    - true
  use_temporal_attention:
    - false
    - false
    - true
    - true
  use_positional_encoding: true
  num_attention_heads: 8
  normalize_qk: true
  cond_resize_method: "nearest"
  cond_embedding_dim: 128

training:
  work_dir: "/super_resolution/training/work_dir/nao_7d_t2m_w10m_q1000_msl"
  total_train_steps: 100000
  checkpoint_every_n_steps: 500
  checkpoint_max_to_keep: 5
  trainer_rng_seed: 56
  lr_initial: 0.0
  lr_peak: 0.0001
  lr_end: 0.0000001
  lr_warmup_steps: 1000
  clip_grad_norm: 0.6
  train_max_noise_level: 80.0
  ema_decay: 0.9999
  eval_every_n_steps: 1000
  eval_num_batches_per_step: 1
  eval_denoise: true
  eval_sampling: true
  eval_num_sde_steps: 64
  eval_num_samples_per_condition: 1
  eval_cfg_strength: 0.2
  eval_likelihood: false
